public enum TutorialPart
{
    Introduction,
    UnitStats,
    Goal,
    MoveUnit,
    Turns,
    Attacking,
    CaptureVillage,
    Villages,
    RecruitingUnits,
    UnitTypes,
    UnitAffinities,
    UnitAbilities,
    TopUI,
    TerainTypes,
    InspectTerrain,
    ToggleUnitDetails,
    DefeatEnemy
}